#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_media_index:
  path: /media/index
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\MediaController::index
